### ISSUE TITLE
How do we want to structure testcases?

### ISSUE THREAD

**Issue by mrecachinas** [erip/rusty_nltk#2]
Here's a reference point:

http://smallcultfollowing.com/rust-int-variations/isize-usize/guide-testing.html

**Comment by erip** [comment]
I think it would make a lot of sense to have in the `src/` directories a `test_{specific_module}.rs` 

```
#[cfg(test)]
mod test_specific_module {
    #[test]
    fn test_foo_in_specific_module() {
        // test foo here
    }
}
```

This would certainly bloat the repo with tests, but it keeps it independent from the source, which I think is quite important. This test modules can also serve as documentation for the API, which is where potential users would look when asking "How do I use this module/function?"

This seems to be the most idiomatic **unit testing** approach in Rust.

**_Integration tests_** would sit in `test/` next to `src/`.

**Comment by mrecachinas** [comment]
@erip I asked this question in #rust-beginners on irc.mozilla.org, and one of the moderators pointed me to https://doc.rust-lang.org/book/testing.html#the-tests-module.

Me:
> Hey, quick question regarding how to setup a library with tests (and cargo): If I have a project setup under `proj/`, where the source is in `proj/src/`, containing multiple subdirectories and submodules all included in `src/lib.rs`, what's the most idiomatic way to add unit tests to each submodule? 

Mod:
> unit tests usually just go with the code itself 
> check out https://doc.rust-lang.org/book/testing.html#the-tests-module 

Me:
> so, I came across that earlier, but does this mean if I have `proj/src/foo/{mod, bar, baz}.rs`, I should include tests within bar.rs and baz.rs? 

Mod:
> i would say that that's the default, generally, yes
> this is for unit tests. functional/integration style tests go in the tests directory 
> due to this module pattern, you _can_ split them out into files if you want 
> like any module 
> i would say that generally, they're kept in the same file unless it's huge 

Me:
> okay, that's what I figured -- if they are huge, would you suggest one test.rs or test_bar.rs, test_baz.rs, etc.? 

Mod:
> well, given that they're a submodule, you end up doing bar/{mod,tests}.rs

**Comment by mrecachinas** [comment]
I think we've got a solid way of doing this. We can revisit this issue later if we desire, but I'm going to go ahead and close this.
